/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\\public\\models\./models\Paperairplane.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Airplane(props) {
  const { nodes, materials } = useGLTF('./models/Paperairplane.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PaperPlane_GEO.geometry} material={materials.initialShadingGroup} />
    </group>
  )
}

useGLTF.preload('./models/Paperairplane.glb')
