/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\\public\\models\\Cloud.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud(props) {
  const { nodes, materials } = useGLTF('./models/Cloud.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.lambert2SG} />
    </group>
  )
}
useGLTF.preload('./models/Cloud.glb')
// public/models/Cloud.glb
// '../../../public/models/Cloud.glb' 
